const mongoose = require('mongoose');
const Counter = require('./Counter');

const productTransformationSchema = new mongoose.Schema({
  // Transformation Details
  transformationNumber: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    sparse: true, // Allow multiple null/undefined values
    trim: true
    // Auto-generated: TRANS-YYYYMMDD-XXXX
  },
  
  // Base Product (source)
  baseProduct: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true,
    index: true
  },
  baseProductName: {
    type: String,
    required: true,
    trim: true
  },
  
  // Target Variant (destination)
  targetVariant: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ProductVariant',
    required: true,
    index: true
  },
  targetVariantName: {
    type: String,
    required: true,
    trim: true
  },
  
  // Transformation Details
  quantity: {
    type: Number,
    required: true,
    min: 1
  },
  
  // Cost Information
  unitTransformationCost: {
    type: Number,
    required: true,
    min: 0
    // Cost per unit to transform
  },
  totalTransformationCost: {
    type: Number,
    required: true,
    min: 0
    // quantity * unitTransformationCost
  },
  
  // Stock Levels Before Transformation
  baseProductStockBefore: {
    type: Number,
    required: true,
    min: 0
  },
  baseProductStockAfter: {
    type: Number,
    required: true,
    min: 0
  },
  variantStockBefore: {
    type: Number,
    required: true,
    min: 0
  },
  variantStockAfter: {
    type: Number,
    required: true,
    min: 0
  },
  
  // Transformation Type
  transformationType: {
    type: String,
    required: true,
    enum: ['color', 'warranty', 'size', 'finish', 'custom'],
    index: true
  },
  
  // Notes
  notes: {
    type: String,
    trim: true,
    maxlength: 1000
  },
  
  // Status
  status: {
    type: String,
    enum: ['pending', 'in_progress', 'completed', 'cancelled'],
    default: 'pending',
    index: true
  },
  
  // Employee/User who performed transformation
  performedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // Date Information
  transformationDate: {
    type: Date,
    default: Date.now,
    index: true
  },
  completedAt: {
    type: Date
  }
}, {
  timestamps: true
});

// Indexes
// transformationNumber index removed - already has unique: true in field definition
productTransformationSchema.index({ baseProduct: 1, status: 1 });
productTransformationSchema.index({ targetVariant: 1, status: 1 });
productTransformationSchema.index({ transformationDate: -1 });
productTransformationSchema.index({ performedBy: 1, transformationDate: -1 });

// Pre-save middleware to generate transformation number using atomic Counter
productTransformationSchema.pre('save', async function(next) {
  if (this.isNew && !this.transformationNumber) {
    try {
      const today = new Date();
      const year = today.getFullYear();
      const month = String(today.getMonth() + 1).padStart(2, '0');
      const day = String(today.getDate()).padStart(2, '0');
      
      // Use atomic counter for date-based transformation numbers
      // Counter key format: transformationNumber_YYYYMMDD
      const counterKey = `transformationNumber_${year}${month}${day}`;
      
      // Atomically increment counter using findOneAndUpdate
      const counter = await Counter.findOneAndUpdate(
        { _id: counterKey },
        { $inc: { seq: 1 } },
        { upsert: true, new: true }
      );
      
      this.transformationNumber = `TRANS-${year}${month}${day}-${String(counter.seq).padStart(4, '0')}`;
    } catch (err) {
      console.error('Error generating transformation number:', err);
      // Fallback: generate based on timestamp if Counter fails
      const today = new Date();
      const year = today.getFullYear();
      const month = String(today.getMonth() + 1).padStart(2, '0');
      const day = String(today.getDate()).padStart(2, '0');
      const timestamp = Date.now().toString().slice(-4);
      this.transformationNumber = `TRANS-${year}${month}${day}-${timestamp}`;
    }
  }
  next();
});

// Method to calculate total cost
productTransformationSchema.methods.calculateTotalCost = function() {
  this.totalTransformationCost = this.quantity * this.unitTransformationCost;
  return this.totalTransformationCost;
};

module.exports = mongoose.model('ProductTransformation', productTransformationSchema);

